# NOTE: update this with your service name
service: users

frameworkVersion: '2'

# Load .env as environment variables
useDotenv: true

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:stage}
  region: ${env:region}
  versionFunctions: false

  environment:
    tableName: ${self:service}-${self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:*'

functions:
  get:
    handler: get.main
    events:
      - http:
          path: users/{id}
          method: get
  create:
    handler: create.main
    events:
      - http:
          path: users/
          method: post
