# NOTE: update this with your service name
service: users

frameworkVersion: '2'

# Load .env as environment variables
useDotenv: true

# Create an optimized package for our functions
package:
  individually: true

plugins:
  # - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:stage}
  region: ${env:region}
  versionFunctions: false

  environment:
    tableName: ${self:service}-${self:provider.stage}

  iamRoleStatements:
    - ${file(../../shared/resources/serverless.common.yml):dynamoDbIamPolicies}

functions:
  get:
    handler: events/get.main
    events:
      - http:
          path: users/{id}
          method: get
  create:
    handler: events/create.main
    events:
      - http:
          path: users/
          method: post
